name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # ou master, dependendo da sua branch principal

# Define permissões necessárias para o GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Faz checkout completo para evitar problemas com histórico

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # A pasta que contém os arquivos estáticos
          clean: true # Limpa o branch de destino antes de fazer deploy
          branch: gh-pages # A branch onde o site será publicado
          token: ${{ secrets.GITHUB_TOKEN }} # Token automático fornecido pelo GitHub
