name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # ou master, dependendo da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # A branch onde o site será publicado
          folder: . # A pasta que contém os arquivos estáticos
          clean: true # Limpa a branch gh-pages antes de fazer deploy